import moment from 'moment';

export const DEFAULT_LEB_TEST_DATA = {
	name: '',
	date: moment().format('YYYY-MM-DD'),
	hemoglobin: '',
	leukosit: '',
	trombosit: '',
	mvc: '',
	mch: '',
	mchc: '',
	eosinofil: '',
	basofil: '',
	nbatang: '',
	nsegmen: '',
	limfosit: '',
	monosit: '',
	kalium: '',
	natrium: '',
	klorida: '',
	igm: '-',
	igg: '-',
	hcv: '-',
	hbsag: 'Non Reaktif',
	btotal: '',
	bdirekt: '',
	bindirekt: '',
	sgot: '',
	sgpt: '',
	albumin: '',
	gds: '',
	ur: '',
	cr: '',
	isUseAntiDengue: false,
	isUseHCV: false,
	isUseHBSAG: false,
	isUseBil: false,
	isUseSGOTSGPT: false,
	isUseAlbumin: false,
	isUseGDS: false,
	isUseUrCr: false,
};
